#!/usr/bin/env python3
"""Add Jobs session (2026-02-10) Q&A rows to SHRSS_Adobe_KT_Session_Follow_Up_Tracker.xlsx."""
from pathlib import Path
import openpyxl

DIR = Path(__file__).resolve().parent
WB_PATH = DIR / "SHRSS_Adobe_KT_Session_Follow_Up_Tracker.xlsx"
SESSION_DATE = "2026-02-10"

# Rows: Question/Comment, Date Asked, Asked By, Answer, Answered On, Answered By, Status, Notes
ROWS = [
    (
        "You have two IDs—job unique ID and job ID. Which one are you using? (Displayed one is wrong.)",
        SESSION_DATE,
        "Mayte Eme",
        "Right now both come from Workday; what's displayed to end user is job ID. Ticket exists for this; dev team looking at it.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "Mayte said 'that's the wrong one'—job ID vs job unique ID; fix via ticket.",
    ),
    (
        "Image field—not mapped to pick up automatically the right image like we currently have?",
        SESSION_DATE,
        "Mayte Eme",
        "Image is author-input; image configuration page allows setting images per property; author can overwrite or remove.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "Does the image override replace the image on the card and the listing or just the card?",
        SESSION_DATE,
        "Lisa Cardia",
        "Override updates image in both job listings component (cards) and job search component (horizontal cards).",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "Lisa noted they typically use logo on listings, property shot on homepage/hiring events.",
    ),
    (
        "If we override something in the CF, does the sync overwrite it or do we keep the override?",
        SESSION_DATE,
        "Mayte Eme",
        "Only Workday fields get overwritten. Image, is hot job, and LD JSON are author-only and do not get overwritten by sync.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "What is the standard size for the logo image that should be uploaded?",
        SESSION_DATE,
        "Ramona Harris",
        "Still need to get back—used whatever was in DAM for Sage site; don't have exact measurements yet.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "",
    ),
    (
        "How do you create a new job as an author (not from Workday)?",
        SESSION_DATE,
        "Mayte Eme",
        "Create → Content Fragment → select Jobs; fill out all fields. Categories are not dropdowns—must match exact value (e.g. casino sales).",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "Is there scheduling when adding a job—as soon as you publish it goes live?",
        SESSION_DATE,
        "Mayte Eme",
        "Content fragments can be scheduled; Workday jobs get published automatically on sync without author intervention.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "Manual jobs—they drop off based on Workday; if manual, we have to manually delete?",
        SESSION_DATE,
        "Mayte Eme",
        "Correct.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "When sync runs from Workday, do we delete all job postings from AEM each time? Job no longer active in Workday—removed on next sync?",
        SESSION_DATE,
        "Gonzalo Calasich (SHRSS)",
        "Folder structure stays; job postings come and go based on Workday. When job removed in Workday, next sync removes it from AEM.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "Do we have an option to immediately hide a job from the website without Workday removing it? (e.g. weekend, can't get hold of anyone.)",
        SESSION_DATE,
        "Mayte Eme",
        "Author could delete but sync would republish. No current way to just hide. Daniela to check with dev team if turning off 'is API data' could freeze sync for that job.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "Edge case but has happened; need business continuity.",
    ),
    (
        "Which fields do not get overridden when sync happens? (You said three.)",
        SESSION_DATE,
        "Lisa Cardia",
        "Image, is hot job, and LD JSON. Only those three are author-only.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "Select locations in job search—are those pulling from AEM? New property—is author responsible for adding so it appears in filter?",
        SESSION_DATE,
        "Ramona Harris",
        "Locations come from content fragment (country, state, city). New property/jobs from Workday create folder structure automatically; author does not add.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "Ramona had not seen Ottawa in AEM—clarified it's from CF data.",
    ),
    (
        "For the image in the component—where does it come from? If we move the asset in DAM, do we lose the reference?",
        SESSION_DATE,
        "Don Middlebrook",
        "Image comes from DAM. If asset moved or renamed, reference should update; if deleted, would break. Daniela to confirm.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "",
    ),
    (
        "How is the sequence/order of job results determined? How would we reorder?",
        SESSION_DATE,
        "Charles Baugh (SHRSS)",
        "Sort filter on component: most recent (default), job title, location. Hot jobs always stay at top; rest sort among themselves.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "When clicking a job card—what data do we send to Tealium data layer? Do we have unique IDs per card for tracking?",
        SESSION_DATE,
        "Mayte Eme",
        "Daniela to check with tech team. Content fragments have unique IDs; need to confirm what is passed to data layer.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "Mayte: need unique IDs per card, not just friendly link.",
    ),
    (
        "Is there an option to run the Workday sync on demand?",
        SESSION_DATE,
        "Angelika Akopyan (SHRSS)",
        "Daniela to check. May be running more frequently than 30 min (e.g. 5 min); will confirm and ask about on-demand.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "",
    ),
    (
        "Production sync—how long will the period be (5 min or 30)? With ~800 jobs, how long does full sync take?",
        SESSION_DATE,
        "Angelika Akopyan (SHRSS)",
        "Daniela to check with team.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "",
    ),
    (
        "When you select a filter it doesn't append to URL. Can we have deep links so copying URL lands on filtered view? (We need friendly deep links, not weird numbers.)",
        SESSION_DATE,
        "Gonzalo Calasich (SHRSS)",
        "Daniela to talk to tech team. Use case: property sites link to careers filtered by property/category/region.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "Mayte: we don't want every filter combo creating new URL (analytics); we want ability to deep link.",
    ),
    (
        "If sync goes wrong and can't display data—do we have an error message or just blank?",
        SESSION_DATE,
        "Mayte Eme",
        "No jobs in AEM shows 'no jobs found.' Separate error message for sync failure (vs no results) is a gap—note for gap analysis.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "Mayte: had blank page when testing iSense; want custom message for business continuity.",
    ),
    (
        "For a new careers page—what template should we use?",
        SESSION_DATE,
        "Lisa Cardia",
        "Open page template for all these pages (header/footer + content area).",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "When you select filters, do they update each other (conditional/dependent filters)?",
        SESSION_DATE,
        "Mayte Eme",
        "Yes—e.g. selecting property updates other filter options; unchecking brings categories back.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "Job listings—does it only go by state (e.g. Florida) or can we select properties? Can we do multiple properties?",
        SESSION_DATE,
        "Mayte Eme",
        "Can select one folder (e.g. Orlando or Florida). You can only select ONE root path, not multiple properties. To show Coco + Classic + Hollywood would require multiple components one after another; can't sort across them.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "Mayte: our use case is three South Florida properties; noted as gap.",
    ),
    (
        "If we have fewer than three cards (e.g. one or two), is there a way to center them instead of left align?",
        SESSION_DATE,
        "Lisa Cardia",
        "Not currently. Would need to discuss in gap portion—centered vs same width vs full width.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "Lisa: hot jobs vs hiring events cards all display differently; consistency concern.",
    ),
    (
        "Apply Now button—what is its purpose if the URL always comes from the content fragment?",
        SESSION_DATE,
        "Lisa Cardia",
        "Button text is configurable in component; the URL/destination is from the content fragment.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "For hot jobs can we have the root path higher so it's all hot jobs, not specific to one location?",
        SESSION_DATE,
        "Mayte Eme",
        "Yes—set root path higher in hierarchy to get all hot jobs across locations.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "If there are no hot jobs—does the component hide, or show blank with a message?",
        SESSION_DATE,
        "Mayte Eme",
        "Currently shows section title with no cards and no message. Does not hide. Angelika confirmed; Mayte/Lisa want hide or message—gap.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "JIRA ticket exists for this.",
    ),
    (
        "Hot jobs we use property image; in listings we use logo. Same job in hot jobs vs listing—we want different images.",
        SESSION_DATE,
        "Lisa Cardia",
        "Noted. Daniela confirmed understanding—hot job might have property image, same job in search shows logo. Gap for implementation.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "",
    ),
    (
        "Why do we have to configure the search page in Job Filters? We only have one search page. Can it be defaulted?",
        SESSION_DATE,
        "Mayte Eme",
        "Currently pointing to correct page. If component used elsewhere, author can change. Defaulting is possible; Mayte wants one step less for authors. Log as gap.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "",
    ),
    (
        "Job category cards—how do we change/pick which categories to display? (e.g. don't want food and beverage, want to promote others.)",
        SESSION_DATE,
        "Mayte Eme",
        "Currently cannot pick and choose categories; shows all or by sort (most jobs / alphabetical). Not in component.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "Mayte: we had ability in past; this component may be deprecated.",
    ),
    (
        "What is 'job property' in the image config? Is it a specific name we need to match (e.g. Workday name)?",
        SESSION_DATE,
        "Mayte Eme",
        "It's the value from the job property field in the content fragment. Config matches that value to assign the image. Must match exactly.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "Are all locations in the image config? We have over 500 locations; the list doesn't seem long.",
        SESSION_DATE,
        "Mayte Eme",
        "Initial setup by Adobe tech team; list may not be complete. Need full list—Lucas to follow up with Vinay; Scott to task IT to get list from Workday and map ahead of time.",
        SESSION_DATE,
        "Daniela Tea / Lucas Nelson",
        "Pending",
        "Lisa: mapping has to be manually added in AEM; Workday doesn't push it.",
    ),
    (
        "If Workday changes internal name (e.g. HRC Washington DC to Hard Rock Cafe Washington DC), does that break the mapping?",
        SESSION_DATE,
        "Mayte Eme",
        "New entry would need to be added in config with the new property value and desired logo. Old name would no longer match.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "Mayte: mapping is very manual; concern for 500+ locations.",
    ),
    (
        "Who does the mapping and who gets every location name when we go to production?",
        SESSION_DATE,
        "Mayte Eme",
        "Adobe did initial setup. Who adds new properties or changes logos unclear; need to understand source of full list.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "Scott to ask Vinay; Lisa: whoever handed off first time.",
    ),
    (
        "Hot jobs page and hiring events page—do we have to add hot jobs manually to every location or does it pull from same feed?",
        SESSION_DATE,
        "Lisa Cardia",
        "Same component (job listings, hot jobs). Toggle hot job in CF once; appears on homepage and hot jobs page. Hiring events = different content fragment (events session).",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "",
    ),
    (
        "On the hot jobs page—where is the filtering and searching?",
        SESSION_DATE,
        "Mayte Eme",
        "Filtering is not currently part of the component; open ticket, gap in JIRA.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "",
    ),
    (
        "Hiring events cards vs hot jobs—different widths/heights; not consistent.",
        SESSION_DATE,
        "Lisa Cardia",
        "Different content fragments; will cover events tomorrow. Noted inconsistency.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "",
    ),
    (
        "Queries for bringing in different content by property (like Sitecore scopes)—will we go through that?",
        SESSION_DATE,
        "Mayte Eme",
        "Daniela asked for examples. Angelika showed brands/cafes/casinos—same cards on multiple pages. Experience Fragment approach can give single update; exclusion logic (e.g. don't show current page's card) would need custom logic.",
        SESSION_DATE,
        "Daniela Tea",
        "Answered",
        "Lisa: need logic so on Casinos page we don't show Casinos card (show children excluding current).",
    ),
    (
        "Shared cards—when on casino page, don't show casino card (show all children excluding current page). Experience fragment gets us reuse; we need that exclusion logic.",
        SESSION_DATE,
        "Lisa Cardia",
        "Experience fragment = update once. Current implementation is local per page so exclusion was possible. To get both reuse and exclusion would need custom component. Decision for Hard Rock.",
        SESSION_DATE,
        "Daniela Tea",
        "Deferred",
        "Mayte: should have been set up properly; task for Mohsin.",
    ),
    (
        "Best way to take down 3 jobs and reschedule for later—resubmit through Workday with 10 and purge, or purge in AEM, or reschedule manually in AEM?",
        SESSION_DATE,
        "Charles Baugh (SHRSS)",
        "Workday is source of truth; AEM changes get overwritten by sync. Daniela to check with tech team if there's an author-side way to handle; answer tomorrow.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "",
    ),
    (
        "Job filters (homepage)—where are the four labels (job category label, properties label, etc.) located in configuration? I had a story and couldn't find them.",
        SESSION_DATE,
        "Joseph Brondolo (SHRSS)",
        "Daniela to get back—might be in markup not visible to user. Add to list for beginning of tomorrow's session.",
        SESSION_DATE,
        "Daniela Tea",
        "Pending",
        "",
    ),
    (
        "Did we ask for specs for the job/logo images so we don't have corrupt or huge logos? Who fixes those before go-live?",
        SESSION_DATE,
        "Mayte Eme",
        "Spec sheet not yet detailed. Lucas: Daniela to talk with Vinay and authoring support.",
        SESSION_DATE,
        "Daniela Tea / Lucas Nelson",
        "Pending",
        "",
    ),
    (
        "Pagination—recommendation for max number of jobs per page? We have ~800 jobs; have you tested performance?",
        SESSION_DATE,
        "Mayte Eme",
        "Lucas: Adobe doesn't have performance testing resource. Scott: take back to TJ/Mohsin. Mayte: had issues before with 50; want an answer.",
        SESSION_DATE,
        "Lucas Nelson / Scott Sorel",
        "Pending",
        "",
    ),
    # Product Director (persona) questions
    (
        "Governance: Who owns ongoing maintenance of job property–to–image mapping (Adobe, IT, or SHRSS)? What process for new properties or Workday name changes?",
        SESSION_DATE,
        "Product Director",
        "Not answered in session. Initial setup by Adobe; full list and process to be confirmed (Vinay, IT).",
        "",
        "",
        "Pending",
        "Product Director persona—governance and roles.",
    ),
    (
        "Authoring: Can we get a short checklist or decision tree for authors (which component when; what authors can edit vs what sync overwrites)?",
        SESSION_DATE,
        "Product Director",
        "Not answered in session.",
        "",
        "",
        "Pending",
        "Product Director persona—authoring clarity.",
    ),
    (
        "Tagging/metadata: Besides Hot Job and image, what other author-controlled metadata affects display or filtering? Who governs allowed values for categories (Workday vs author-created)?",
        SESSION_DATE,
        "Product Director",
        "Not answered in session. Categories from Workday; author-created jobs must match exact category string.",
        "",
        "",
        "Pending",
        "Product Director persona—tagging and governance.",
    ),
    (
        "Gap analysis: Which of today's gaps are in scope for careers go-live (e.g. job ID, deep links, hot jobs empty state, image specs) vs deferred to post–gap analysis?",
        SESSION_DATE,
        "Product Director",
        "Not explicitly listed in session. Many items taken as follow-up or gap analysis.",
        "",
        "",
        "Pending",
        "Product Director persona—priorities for go-live.",
    ),
    (
        "Permissions: Who can access Job Image configuration (ACS AEM Commons)? Admin-only or can we assign a careers/DAM role?",
        SESSION_DATE,
        "Product Director",
        "Not answered in session.",
        "",
        "",
        "Pending",
        "Product Director persona—governance and permissions.",
    ),
]

def main():
    wb = openpyxl.load_workbook(WB_PATH)
    ws = wb["Jobs"]
    next_row = ws.max_row + 1
    for row in ROWS:
        for col, val in enumerate(row, 1):
            ws.cell(row=next_row, column=col, value=val)
        next_row += 1
    wb.save(WB_PATH)
    print(f"Added {len(ROWS)} rows to Jobs sheet. Total data rows: {len(ROWS)}")

if __name__ == "__main__":
    main()
